### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by maxdeviant** [Ebmtranceboy/purescript-geometry-plane#1]
It doesn't appear that this package is currently licensed under any sort of open source license.

Would it be possible to add a license?

### Motivation

`geometry-plane` is currently in the PureScript [package set](https://github.com/purescript/package-sets) and will need to have this license issue addressed in order to remain in the package set after the move to the new PureScript registry.

See https://github.com/purescript/registry/issues/250 for more details.

**Comment by Ebmtranceboy** [comment]
I've added a license, created a new tag (v1.0.2), updated package-sets/packages.json and created a PR but there seems to be an issue with the checks.

**Comment by maxdeviant** [comment]
> I've added a license, created a new tag (v1.0.2), updated package-sets/packages.json and created a PR but there seems to be an issue with the checks.

Thank you! I will take a look at the package sets PR to see what the issue is.

I'll close this issue out since you've added the license 🙂
